name: 'Digital.ai Deploy Integration'
description: 'Github Actions for Digital.ai Deploy'
author: 'Digital.ai'
branding:
  color: 'green'
  icon: 'upload-cloud'

inputs:
  serverUrl:
    description: 'The URL of the Digital.ai Deploy server.'
    required: true
  username:
    description: 'The username for authenticating with Digital.ai Deploy.'
    required: true
  password:
    description: 'The password for authenticating with Digital.ai Deploy.'
    required: true
  action:
    description: 'Action to perform: create, publish, deploy. Default is create, publish, and deploy.'
    required: false
    default: 'create_publish_deploy'    
  manifestPath:
    description: 'The path to the deployit-manifest.xml file.'
    required: false
  outputPath:
    description: 'The path for storing the newly created DAR package.'
    required: false
  packageName:
    description: 'The name of the newly created DAR package.'
    required: false    
  versionNumber:
    description: 'Specify a version number to set in your manifest file.'
    required: false    
  darPackagePath:
    description: 'The path to the DAR package.'
    required: false
  deploymentPackageId:
    description: 'The ID of the package to be deployed.'
    required: false
  environmentId:
    description: 'ID of the target environment in Digital.ai Deploy.'
    required: false
  rollback:
    description: 'Invoke a rollback in case of deployment failure.'
    required: false

outputs:
  deploymentPackageId:
    description: 'The ID of the published package.' 
  darPackagePath:
    description: 'The relative path to the DAR package created by the action.'  

runs:
  using: 'node20'
  main: 'dist/index.js'